apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: investment-data-docker-graph
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
